
typedef _Bool bool;
typedef unsigned long size_t;
typedef long ssize_t;
typedef int int32_t;
typedef unsigned int uint32_t;
typedef long long int64_t;
typedef unsigned long long uint64_t;
typedef short int16_t;
typedef unsigned short uint16_t;
typedef char int8_t;
typedef unsigned char uint8_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;

typedef struct VampireSurvivors_Objects_BasePoolableSpriteBehaviour_Fields{
	int64_t filler[9];
}VampireSurvivors_Objects_BasePoolableSpriteBehaviour_Fields;

typedef struct UnityEngine_Quaternion_o{
	int64_t filler[2];
}UnityEngine_Quaternion_o;

typedef struct UnityEngine_Vector2_o{
	int64_t filler[1];
}UnityEngine_Vector2_o;

typedef struct System_Nullable_float__o{
	int64_t filler[1];
}System_Nullable_float__o;

struct GameMonoBehaviour_Fields{
	int64_t filler[2];
};

struct UnityEngine_Rect_o{
	int64_t filler[2];
};

struct ArcadeSprite_Fields{
	int64_t filler[8];
};

struct VampireSurvivors_Objects_Stage_Fields {
	struct GameMonoBehaviour_Fields filler;
	struct VampireSurvivors_Objects_TilingBackground_o* _TilingBackgroundPrefab;
	struct VampireSurvivors_Objects_TilingTileset_o* _TilingTilesetPrefab;
	struct UnityEngine_Transform_o* _LevelTransform;
	int32_t _stageType;
	int32_t _currentMinute;
	int32_t _maximum;
	int32_t _lastMinimum;
	int32_t _lastMaximum;
	int32_t _defaultMaximum;
	float _minMultiplier;
	float _effectiveSpawnFrequency;
	struct Newtonsoft_Json_Linq_JObject_o* _stageJsonData;
	struct VampireSurvivors_Data_Stage_StageData_o* _stageData;
	struct VampireSurvivors_Data_Stage_StageData_o* _baseStageData;
	struct VampireSurvivors_App_Objects_StageModifiers_o* _stageMods;
	bool _hasTileSet;
	int32_t _spawnType;
	bool _hasAttachedTreasure;
	bool _compressTime;
	float _pizzaDelay;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _pauseTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _spawnTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _destructibleTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _checkPizzasTimer;
	struct System_Collections_Generic_List_Vector2__o* _enemySpawnLocations;
	struct System_Collections_Generic_List_Vector2__o* _destructibleLocations;
	struct System_Collections_Generic_List_Vector2__o* _cartLocations;
	struct System_Collections_Generic_List_Vector2__o* _windowLocations;
	struct System_Collections_Generic_List_Vector2__o* _pizzaLocations;
	struct System_Collections_Generic_List_PizzaCircle__o* _pizzaCircles;
	struct System_Collections_Generic_List_Vector2__o* _tiledPositions;
	struct System_Collections_Generic_List_Rectangle__o* _noShadowLocations;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _noShadowsTimer;
	bool _shadowsVisible;
	struct VampireSurvivors_Framework_PhaserTweens_MultiTargetTween_o* _shadowsTween;
	struct UnityEngine_Rect_o _spawnOuterRect;
	struct UnityEngine_Rect_o _spawnInnerRect;
	struct UnityEngine_Rect_o _enemiesDespawnRect;
	struct UnityEngine_Rect_o _containmentScreenRect;
	struct UnityEngine_Rect_o _containmentExactRect;
	struct UnityEngine_Rect_o _tiledOuterRect;
	struct UnityEngine_Rect_o _tiledInnerRect;
	struct System_Collections_Generic_List_EnemyController__o* _spawnedEnemies;
	struct System_Collections_Generic_List_Collider2D__o* _enemySearchResults;
	struct System_Collections_Generic_List_Collider2D__o* _overlapResults;
	bool _hasWallsCheckDestructibleLogic;
	bool _isCharmApplied;
	struct UnityEngine_Transform_o* _cachedTransform;
	struct UnityEngine_Camera_o* _mainCamera;
	struct Zenject_SignalBus_o* _signalBus;
	struct VampireSurvivors_Data_DataManager_o* _dataManager;
	struct VampireSurvivors_Objects_PlayerOptions_o* _playerOptions;
	struct VampireSurvivors_Objects_StageEventManager_o* _stageEventManager;
	struct VampireSurvivors_Objects_StageEventTrisectionManager_o* _trisection;
	struct VampireSurvivors_App_Scripts_Objects_StageEventTwitchManager_o* _stageEventTwitchManager;
	struct VampireSurvivors_Framework_GameSessionData_o* _gameSessionData;
	struct Zenject_DiContainer_o* _diContainer;
	struct VampireSurvivors_Objects_TilingBackground_o* _tilingBackground;
	struct VampireSurvivors_Objects_TilingTileset_o* _tilingTileset;
	struct VampireSurvivors_App_Framework_EnemyFactory_o* _enemyFactory;
	struct VampireSurvivors_Framework_DestructibleFactory_o* _destructibleFactory;
	struct VampireSurvivors_Framework_ArcanaManager_o* _arcanaManager;
	struct VampireSurvivors_Objects_Stages_BackgroundManager_o* _fancyBg;
	struct VampireSurvivors_Framework_GameManager_o* _gameManager;
	struct System_Collections_Generic_List_Nullable_EnemyType___o* _enemyTypes;
	struct System_Collections_Generic_List_Nullable_EnemyType___o* _bossTypes;
	struct System_Collections_Generic_Dictionary_EnemyType__bool__o* _enemyPoolStates;
	struct System_Collections_Generic_Dictionary_EnemyType__bool__o* _bossPoolStates;
	float _ShadowAlpha;
	float _SoleShadowAlpha;
	bool _HasInitialized_k__BackingField;
	float _EnemyHealthMultiplier_k__BackingField;
	float _EnemySpeedMultiplier_k__BackingField;
	int32_t _MaxDestructibles_k__BackingField;
	float _Pause_k__BackingField;
	bool _StopCheckingMinutes_k__BackingField;
	struct System_Nullable_float__o _MinTreasureY_k__BackingField;
	struct System_Nullable_float__o _MaxTreasureY_k__BackingField;
	struct System_Nullable_float__o _MinTreasureX_k__BackingField;
	struct System_Nullable_float__o _MaxTreasureX_k__BackingField;
	bool _IsMerchantBanned_k__BackingField;
	int32_t _cullIterator;
	struct System_Collections_Generic_List_EnemyController__o* _enemiesToCull;
};
struct VampireSurvivors_Objects_Characters_EnemyController_Fields {
	VampireSurvivors_Objects_BasePoolableSpriteBehaviour_Fields filler;
	struct UnityEngine_SpriteRenderer_o* _EnemyRenderer;
	struct UnityEngine_SpriteRenderer_o* _AlertSpriteRenderer;
	struct VampireSurvivors_Graphics_SpriteAnimation_o* _SpriteAnimation;
	struct Zenject_SignalBus_o* _signalBus;
	struct UnityEngine_Transform_o* _cachedTransform;
	struct VampireSurvivors_Framework_GameSessionData_o* _gameSessionData;
	struct VampireSurvivors_Framework_GameManager_o* _gameManager;
	struct VampireSurvivors_Data_DataManager_o* _dataManager;
	struct Newtonsoft_Json_Linq_JObject_o* _currentJsonData;
	struct VampireSurvivors_Data_Enemies_EnemyData_o* _currentEnemyData;
	bool _hasInitializedData;
	struct VampireSurvivors_Objects_PlayerOptions_o* _playerOptions;
	struct UnityEngine_Transform_o* _targetTransform;
	bool _receivingDamage;
	bool _passThroughWalls;
	struct VampireSurvivors_Data_Stage_Treasure_o* _treasure;
	bool _selfDestruct;
	bool _isSelfDestructionTriggered;
	float _startingAngle;
	struct DG_Tweening_Sequence_o* _alertTween;
	uint32_t _saveTint;
	struct UnityEngine_Transform_o* _enemyRendererTransform;
	float _wiggleProgress;
	bool _wiggleForward;
	struct UnityEngine_Quaternion_o _wiggleStartRot;
	struct UnityEngine_Quaternion_o _wiggleEndRot;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _selfDestructTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _pushbackTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _freezeTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _blinkTimeout;
	struct UnityEngine_Vector2_o _spritePivot;
	bool _canBeDamagedByBloodline;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _divineBloodlineDamageTimer;
	int32_t _enemyType;
	float _damageKb;
	float _defaultSpeed;
	float _scaleMul;
	bool _hpXLevel;
	bool _fixedDirection;
	bool _medusa;
	float _medusaElapsed;
	struct UnityEngine_GameObject_o* _owner;
	float _alpha;
	struct System_String_o* _defaultName;
	float _damageWeakness;
	float _maxDamageWeakness;
	int32_t _multiplayerCorpseFeedingCounter;
	struct UnityEngine_Vector2_o _currentDirection;
	float _hp;
	float _maxHp;
	float _Speed_k__BackingField;
	bool _IsTeleportOnCull_k__BackingField;
	bool _IsCullable_k__BackingField;
	bool _IsStatic_k__BackingField;
	struct System_Nullable_float__o _ResRosary_k__BackingField;
	struct System_Nullable_float__o _ResDebuffs_k__BackingField;
	struct System_Nullable_float__o _ResCorridor_k__BackingField;
	struct System_Nullable_float__o _ResFreeze_k__BackingField;
	float _Slow_k__BackingField;
	bool _IsPatrolling_k__BackingField;
	float _KnockBack_k__BackingField;
	bool _IsTimeStopped_k__BackingField;
	float _SelfDestDistance_k__BackingField;
	int32_t _StageEventId_k__BackingField;
	bool _ConditionalCanMove_k__BackingField;
	bool _IsDead_k__BackingField;
	int32_t currentDepthEnemy;
	int32_t currentDepthAlert;
};

struct VampireSurvivors_Objects_Characters_CharacterController_Fields {
	struct ArcadeSprite_Fields filler;
	int32_t _PlayerIndex;
	struct UnityEngine_SpriteRenderer_o* _CharacterRenderer;
	struct UnityEngine_SpriteRenderer_o* _DeathNoHurtRenderer;
	struct Zenject_SignalBus_o* _signalBus;
	struct VampireSurvivors_Objects_PlayerOptions_o* _playerOptions;
	struct VampireSurvivors_Framework_GameManager_o* _gameManager;
	struct Rewired_Player_o* _player;
	struct UnityEngine_Transform_o* _cachedTransform;
	struct VampireSurvivors_Objects_CharacterWeaponsManager_o* _weaponsManager;
	struct VampireSurvivors_Objects_CharacterAccessoriesManager_o* _accessoriesManager;
	struct VampireSurvivors_Graphics_SpriteAnimation_o* _spriteAnimation;
	struct UnityEngine_ParticleSystem_o* _damageVfx;
	struct VampireSurvivors_Graphics_SpriteTrail_o* _spriteTrail;
	struct VampireSurvivors_UI_Player_HealthBar_o* _healthBar;
	struct VampireSurvivors_Data_DataManager_o* _dataManager;
	struct Newtonsoft_Json_Linq_JObject_o* _currentJsonData;
	struct VampireSurvivors_Data_Characters_CharacterData_o* _currentCharacterData;
	struct VampireSurvivors_Data_Characters_CharacterData_o* _currentSkinData;
	struct VampireSurvivors_Data_Characters_CharacterData_o* _levelZeroCharacterData;
	struct System_Collections_Generic_List_WeaponType__o* _weaponSelection;
	int32_t _startingWeaponType;
	int32_t _characterType;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _regenTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _blinkTimeoutTimer;
	bool _receivingDamage;
	float _invincibilityTimer;
	bool _hasWalkingAnimation;
	struct VampireSurvivors_Framework_PhaserTweens_MultiTargetTween_o* _wiggleTween;
	struct UnityEngine_Vector2_o _currentDirection;
	struct UnityEngine_Vector2_o _currentDirectionRaw;
	struct UnityEngine_Vector2_o _lastMovementDirection;
	struct UnityEngine_MaterialPropertyBlock_o* _propBlock;
	struct ArcadeBodyBounds_o* _worldBoxCollider;
	struct ArcadeBodyBounds_o* _coopMovementBoxCollider;
	struct VampireSurvivors_Objects_ModifierStats_o* _onEveryLevelUp;
	struct VampireSurvivors_Objects_PlayerModifierStats_o* _playerStats;
	float _slowMultiplier;
	bool _isSlow;
	float _currentHp;
	int32_t _level;
	float _walked;
	struct UnityEngine_Vector2_o _lastFacingDirection;
	float _xp;
	bool _isAnimForced;
	bool _canFlip;
	bool _isFlipped;
	float _shieldInvulTime;
	struct VampireSurvivors_Objects_MagnetZone_o* _magnet;
	struct VampireSurvivors_Objects_SineBonus_o* _sineSpeed;
	struct VampireSurvivors_Objects_SineBonus_o* _sineCooldown;
	struct VampireSurvivors_Objects_SineBonus_o* _sineArea;
	struct VampireSurvivors_Objects_SineBonus_o* _sineDuration;
	struct VampireSurvivors_Objects_SineBonus_o* _sineMight;
	float _slowTime;
	float _gFeverMul;
	struct System_Action_float__o* _onHpRecoveryCallback;
	bool _isInFinalStage;
	bool _isDead;
	bool _isInvul;
	bool _isLastBreathEnabled;
	bool _hasLastBreath;
	struct System_Action_o* _onLastBreath;
	int32_t _maxWeaponCount;
	int32_t _maxAccessoryCount;
	struct VampireSurvivors_UI_Player_MultiplayerRevivalUI_o* _multiplayerRevivalUI;
	struct UnityEngine_SpriteRenderer_o* _multiplayerIndicator;
	struct VampireSurvivors_Objects_Characters_SpriteOutlinerControl_o* _multiplayerOutliner;
	float _multiplayerRevivalProportion;
	int32_t _revivalJuiceThisFrame;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _multiplayerChompTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _multiplayerIndicatorTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _multiplayerDecompositionTimer;
	struct UnityEngine_Transform_o* _multiplayerCameraTargetTransform;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _deathConsequenceTimer;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _multiplayerReviveShake1;
	struct VampireSurvivors_Framework_TimerSystem_Timer_o* _multiplayerReviveShake2;
	bool _multiplayerRevivalAllowed;
	bool _AlwaysCoinBag_k__BackingField;
	bool _AlwaysRoast_k__BackingField;
	bool _AlwaysRandomLimitBreak_k__BackingField;
};